// src/app/blog/tag/[tag]/page.tsx
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getAllTags, getPostsByTagSlug } from "@/lib/blog";
import { getPaletteTagHref } from "@/lib/site-data";
import { formatDisplayDate, startCase } from "@/lib/utils";

export async function generateStaticParams() {
  const tags = await getAllTags();
  return tags.map((tag) => ({
    tag: tag
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .trim(),
  }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ tag: string }>;
}): Promise<Metadata> {
  const { tag } = await params;

  return {
    title: `${startCase(tag)} Articles`,
    description: `Articles tagged ${startCase(tag)} on Look Palette.`,
  };
}

export default async function TagPage({
  params,
}: {
  params: Promise<{ tag: string }>;
}) {
  const { tag } = await params;
  const posts = await getPostsByTagSlug(tag);

  if (!posts.length) {
    notFound();
  }

  return (
    <div className="shell section-space">
      <div className="mb-10 max-w-3xl">
        <p className="eyebrow text-[var(--color-accent)]">Blog Tag</p>
        <h1 className="mt-3 text-4xl font-semibold">{startCase(tag)}</h1>
        <p className="mt-4 text-lg leading-8 text-stone-600">
          Articles related to {startCase(tag)}.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
        {posts.map((post) => (
          <article key={post.slug} className="surface overflow-hidden rounded-[1.75rem]">
            <div className="relative aspect-[1.9/1]">
              <Image
                src={post.image}
                alt={post.title}
                fill
                sizes="(min-width: 1280px) 30vw, (min-width: 768px) 45vw, 100vw"
                className="object-cover"
              />
            </div>
            <div className="p-6">
              <p className="text-sm text-stone-500">
                {post.author} · {formatDisplayDate(post.date)}
              </p>
              <h2 className="mt-3 text-xl font-semibold">
                <Link href={`/blog/${post.slug}`}>{post.title}</Link>
              </h2>
              <p className="mt-3 leading-7 text-stone-600">{post.description}</p>
              <div className="mt-4 flex flex-wrap gap-2">
                {post.tags.map((postTag) => (
                  <Link
                    key={postTag}
                    href={getPaletteTagHref(postTag)}
                    className="rounded-full bg-stone-100 px-3 py-1 text-xs font-semibold text-stone-700"
                  >
                    {postTag}
                  </Link>
                ))}
              </div>
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}

// look-palette-main/src/routes/blog/tag/[tag]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { tagToSlug } from '$lib/functions';

	let { data } = $props<{ data: PageData }>();
	let tag = $derived(data.tag);
	let posts = $derived(data.posts);
</script>

<svelte:head>
	<title>Posts tagged "{tag}" | Look Palette Blog</title>
	<meta name="description" content="Browse all blog posts tagged with {tag} on Look Palette." />
</svelte:head>

<header class="text-center mb-8 relative overflow-hidden bg-gray-800" style="min-height: 300px;">
	<img
		src="/hero/hero-image-blog.avif"
		alt="Blog | Look Palette"
		class="absolute inset-0 w-full h-full object-cover"
	/>

	<div class="relative z-10 py-16 px-8">
		<h1
			class="inter mt-2 text-5xl font-semibold tracking-tight text-pretty text-black sm:text-6xl sm:text-balance"
		>
			{tag}
		</h1>
		<p class="inter text-xl text-black max-w-7xl mx-auto mt-6">
			Posts that are tagged with {tag}
		</p>
	</div>
</header>

<div class="max-w-7xl mx-auto p-8 py-8 sm:py-12">
	<main>
		<div class="mb-8">
			<a href="/blog" class="text-gray-600 hover:text-gray-800 transition-colors">
				← Back to Blog
			</a>
		</div>

		<section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
			{#each posts as post}
				<article
					class="bg-white rounded-lg shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300"
				>
					{#if post.image}
						<img src={post.image} alt={post.title} class="w-full aspect-[1.9/1] object-cover" />
					{/if}

					<div class="p-6">
						<div class="flex items-center text-sm text-gray-600 mb-2">
							<span>By {post.author}</span>
							<span class="mx-2">•</span>
							<time datetime={post.date}>
								{new Date(post.date).toLocaleDateString('en-US', {
									year: 'numeric',
									month: 'long',
									day: 'numeric'
								})}
							</time>
						</div>

						<h2 class="text-xl font-semibold text-gray-900 mb-3 line-clamp-2">
							<a href="/blog/{post.slug}" class="hover:text-gray-700 transition-colors">
								{post.title}
							</a>
						</h2>

						<p class="text-gray-600 mb-4 line-clamp-3">{post.description}</p>

						{#if post.tags && post.tags.length > 0}
							<div class="flex flex-wrap gap-2">
								{#each post.tags as tag}
									<a
										href="/blog/tag/{tagToSlug(tag)}"
										class="px-2 py-1 bg-gray-100 text-gray-700 rounded-full text-xs hover:bg-gray-200 transition-colors"
									>
										{tag}
									</a>
								{/each}
							</div>
						{/if}
					</div>
				</article>
			{/each}
		</section>

		{#if posts.length === 0}
			<div class="text-center py-12">
				<h2 class="text-2xl font-semibold text-gray-900 mb-4">No posts found</h2>
				<p class="text-gray-600 mb-6">No blog posts were found with the tag "{tag}".</p>
				<a
					href="/blog"
					class="inline-flex items-center px-4 py-2 bg-black text-white rounded-lg hover:opacity-80 transition-opacity"
				>
					View all posts
				</a>
			</div>
		{/if}
	</main>
</div>

<style>
	.line-clamp-2 {
		display: -webkit-box;
		-webkit-line-clamp: 2;
		-webkit-box-orient: vertical;
		overflow: hidden;
		line-clamp: 2;
	}

	.line-clamp-3 {
		display: -webkit-box;
		-webkit-line-clamp: 3;
		-webkit-box-orient: vertical;
		overflow: hidden;
		line-clamp: 3;
	}
</style>
